### ISSUE TITLE
[Drupal] Split staging from production environment & feature / version lock

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#102]
Hey Lowell,

Sorry I couldn't make it today. Aaron mentioned we're planning to launch very soon. It feels like now is a good time to setup a separate staging environment from production, so that you can work on/demo stuff and not worry about breaking the real website.
## TODO
- [ ] Setup staging environment
- [ ] Make an easy way (single script?) to copy configuration from staging to production
- [ ] Mental note to only work on bug fixes / stability in the master branch as we're going into launch
- [ ] Hand this someone on the front end (Levi or me) to sync up the [Consumer] dev side to use the staging environment's data
