### ISSUE TITLE
[Consumer] Deal with times & timezones correctly

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#25]
From discussion w/Levi, he's started the date parsing code, but wanted to hand that off to me.

**New**
- [x] Adjust per Lowell's API tweaks May 31st  - https://github.com/codeforeauclaire/foodtrucks/issues/47#issuecomment-222871802 >> update notes here

**Part A**
- [x] Await date format solidify (Comment from Anthony in #18 on 5/23/2016 at 6:50pm)
- [x] Ensure output with correct timezone in bubble (**Addressed by Levi @ https://github.com/codeforeauclaire/foodtrucks/commit/682012dc62b7a438a3294a7fb8e7c56c00b37415)**
  - [x] Tweak timezone to CST (Eau Claire's time), not browser's local
- [x] Test time with different browser timezones (All times should be in local Eau Claire time regardless of browser) - N/A now no longer using local browser time checks
- [x] Indicate timezone in times displayed (Something like CST by the times) -- Done and more @ https://github.com/codeforeauclaire/foodtrucks/commit/77149c73e303b58276ddeb9fff5e542b421e8e09

**Part B**
- [x] Await date filtering to solidify (Comment from Anthony in #18 on 5/23/2016 at 6:50pm)
- [ ] Fix to not filter by date/time of returned data, but instead by what API returns
  - In `consumer-ui/js/index.js` there's code under `$('#dateFilter').change(function (e) {` that date filters by what's in the JSON, should be a whole new JSON request and not filtered based on return.  Moved to https://github.com/codeforeauclaire/foodtrucks/issues/45

Leaving assigned to myself for now, but happy to hand off to someone else if they want to take it (just let me know before coding as I may be working on this)

**Comment by Lowell20** [comment]
the default timestamp is UTC. Since those dates are entered in our timezone, they are output as 5-6 hours earlier.
We have a few options to resolve this. 
1. On the admin site, we can set all entries to use UTC, 
2. or we can adjust the json output based on daylight savings, 
3. or the consumer can adjust the timestamps.

I feel as though each of these options are easy enough, let's decide which is the best choice for us.

**Comment by Lowell20** [comment]
I can put a Z on the end if it helps

**Comment by AnthonyAstige** [comment]
@Lowell20 Digging deeper I think you may already have Drupal outputting a good format. Don't worry about it, at least for now.

**Background**
I'm pretty sure the [Consumer] side's JavaScript side can easily handle UTC (Lowell's option 3), and it sounds like a good standard.

Simply adding a Z to the end looks like [WikiPedia's ISO_8601](https://en.wikipedia.org/wiki/ISO_8601)

![2016-05-23_2140](https://cloud.githubusercontent.com/assets/236039/15490601/1b8c2474-212f-11e6-990b-e0b54a474174.png)

However [Moment has it denoted without a Z](http://momentjs.com/docs/#/parsing/special-formats/)

![2016-05-23_2145](https://cloud.githubusercontent.com/assets/236039/15490662/a9a7bfe8-212f-11e6-8601-0bf5d45f029f.png)

**Comment by levifelling** [comment]
> Ensure output with correct timezone in bubble 

I addressed this in https://github.com/codeforeauclaire/foodtrucks/commit/682012dc62b7a438a3294a7fb8e7c56c00b37415

**Comment by Lowell20** [comment]
I will suggest that we use Eau Claire timezone for all times displayed on the consumer site.
It is awesome that it can use my location timezone, but I think it makes sense to show the time relative to the map.

**Comment by AnthonyAstige** [comment]
@Lowell20 Agreed on Eau Claire time zone for display to consumers.  Noted in part A specs in top comment.
