### ISSUE TITLE
[Consumer] Cleanup /consumer-ui/bin/deploy-to-gh-pages script

### ISSUE THREAD

**Issue by Lowell20** [codeforeauclaire/foodtrucks#37]
is there a way to automate this or do we copy the files in manually and then push to it?

**Comment by AnthonyAstige** [comment]
@Lowell20  - Don't push directly to the gh-pages branch; I've made a script at [/consumer-ui/bin/deploy-to-gh-pages](https://github.com/codeforeauclaire/foodtrucks/blob/master/consumer-ui/bin/deploy-to-gh-pages) that copies from the current clone's branch `/consumer-ui/` folder to the gh-pages branch root folder.  Careful with that script though; it's rough and I suggest reading it before running it (It can mess things up if you have uncommitted changes, and I'm not sure how it would behave if run in a cygwin environment vs a real linux enviornment).

**Comment by AnthonyAstige** [comment]
# TODOs
- [ ] Fix script so it runs for Levi (weird MacOS `/tmp` folder stuff)
- [ ] Add sanity checking to the script so it can be run with confidence of not blowing things up
- [ ] Cleanup the script in general (Maintenance)
- [ ] Document the script
- [ ] Document how to use it somewhere (in a README probably)
