### ISSUE TITLE
[VMS] Get Sass watch working

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#67]
# Sass to CSS
## Todo
- [x] If needed add instructions how to clear cache manually, if not needed skip this (#73 blocking)
- [x] Update [dev instructions](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/README.md#vms-easy-setup-development-environment) to login as 'food' user (#73 blocking) (Moved to #83)
- [x] Confirm new reboot method @ https://github.com/codeforeauclaire/foodtrucks/commit/217e36c337f19d77b857c79335d0bb4fb9e9858c works (#75 blocking)
- [x] When done: Unblock #68 & ping Aaron
## Done
- [x] Confirm server spins up correctly, and that new style is showing there.
- [x] Ruby gems install compasss
- [x] Find `config.rb` and files are relative to that
- [x] Run something like `compass watch` on serve instantiation
- [x] Address TODO's in 027c042b4b7d7de8871982c30c10fcb68b57015e
- [x] Tell Aaron about new install path (or just add a symlink in the installation?)

**Comment by AnthonyAstige** [comment]
@Lowell20 I have a proof of concept `compass watch` I think working with `config.rb` . However it looks like compass outputs to `web/themes/custom/foodtruckstheme/css/style.css` when the website is pulling from `sites/default/files/css/css_6soxaV1Y1p-8tIkndDG-Jn3kZbvUBW_gNB1kplOUFXg.css?o8emma`.  Is there perhaps some drupal caching going on that needs to be turned off for a development environment?

# Screenshots

## `compass watch` working proof of concept

![screenshot from 2016-06-07 09-42-17](https://cloud.githubusercontent.com/assets/236039/15862105/37d5e9ba-2c94-11e6-985d-e9018dd220bf.png)

## CSS we need edited it cached somewhere else?

![screenshot from 2016-06-07 09-42-28](https://cloud.githubusercontent.com/assets/236039/15862125/48d1574a-2c94-11e6-88ba-1a12f6edc9f1.png)

**Comment by Lowell20** [comment]
Drupal does a lot of caching, we can turn most of it off but usually we
need to clear the caches.

On Tue, Jun 7, 2016 at 9:47 AM, Anthony Astige notifications@github.com
wrote:

> @Lowell20 https://github.com/Lowell20 I have a proof of concept compass
> watch I think working with config.rb . However it looks like compass
> outputs to web/themes/custom/foodtruckstheme/css/style.css when the
> website is pulling from
> sites/default/files/css/css_6soxaV1Y1p-8tIkndDG-Jn3kZbvUBW_gNB1kplOUFXg.css?o8emma.
> Is there perhaps some drupal caching going on that needs to be turned off
> for a development environment?
> Screenshots compass watch working proof of concept
> 
> [image: screenshot from 2016-06-07 09-42-17]
> https://cloud.githubusercontent.com/assets/236039/15862105/37d5e9ba-2c94-11e6-985d-e9018dd220bf.png
> CSS we need edited it cached somewhere else?
> 
> [image: screenshot from 2016-06-07 09-42-28]
> https://cloud.githubusercontent.com/assets/236039/15862125/48d1574a-2c94-11e6-88ba-1a12f6edc9f1.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/codeforeauclaire/foodtrucks/issues/67#issuecomment-224304329,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABF1aWw137QjiZAa6W_7e5hxZnRo503nks5qJYSFgaJpZM4IvgJA
> .

## 

Lowell Johnson
715-579-9276
Version3 >>> development - hosting - security - performance

**Comment by AnthonyAstige** [comment]
@Lowell20 It could be helpful for development if you can turn off css caching in the [default config](https://github.com/codeforeauclaire/foodtrucks/issues/73).

**Comment by Lowell20** [comment]
At first glance this was compiling the scss with errors so I disabled it while getting the vms to install cleanly.
Now we can probably test and enable this again.
We can turn off some of the caching, but it is common to have to clear caches manually.
Either visit the configuration/performance page to clear the caches or run `drush cr` from the web directory

**Comment by Lowell20** [comment]
Just tested and looks all good, with compass watch and caching disabled
