### ISSUE TITLE
[Drupal] VMS: Update default config

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#73]
# Todo
- [x] 1. Add SQL dump from http://vendors.foodtrucks.codeforeauclaire.org/?
- [x] 2. Update `vmsquickinstall.sh` as needed? (There is a line `(cd /root/foodtrucks/drupal-project/web drush sqlc < ../db.sql)` but I see no `db.sql` anywhere in the repository)
- [x] 3. Test quickinstall works, drive new action as needed
- [x] 4. Comment on #67 that this issue is no longer blocking it
## Issues I see
1. In the top right hand corner there's only a home link
2. We don't have any demo vendors to login as (have to do `drush uli 1` >> create a user >> give auth >> ...)
3. CSS caching default off needed for development environments (#67)

There's probably more issues
### Screenshots

![screenshot from 2016-06-07 09-01-52](https://cloud.githubusercontent.com/assets/236039/15860399/8b5319c4-2c8e-11e6-8082-b015cc537039.png)

**Comment by AnthonyAstige** [comment]
@Lowell20 See the screenshot above, I think we need an updated (or is there one at all?) sql dump from http://vendors.foodtrucks.codeforeauclaire.org/.  If possible it'd be nice to include the usual 'food' user in it.

**Comment by Lowell20** [comment]
Yes, I will add default content and db in the repo
