### ISSUE TITLE
[Drupal] Fix package versions?

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/foodtrucks#75]
I think there's some package version issues (with composer?).  See the red errors in the attached screenshots.
## TODO
- [x] 1. Resolve this issue
- [x] 2. Confirm a fresh VMS install works (fix any bugs along the way as needed)
- [x] 3. Comment on #67 that this issue is no longer blocking it
## Reproduction

Use [VMS Easy setup development environment](https://github.com/codeforeauclaire/foodtrucks/blob/master/drupal-project/README.md#vms-easy-setup-development-environment).  Optionally skip forking by using `export GHUSER='codeforeauclaire'` in step "2i".
## Log

[log.txt](https://github.com/codeforeauclaire/foodtrucks/files/303042/log.txt)
## Screenshots

![1](https://cloud.githubusercontent.com/assets/236039/15865443/541b7bce-2ca0-11e6-8003-e4e615aaff5d.png)
![2](https://cloud.githubusercontent.com/assets/236039/15865444/541e20ea-2ca0-11e6-8625-28fc37a207ec.png)

**Comment by AnthonyAstige** [comment]
Reading some of the non-red stuff, I'm gonna try to install `php-dom` and see if that helps resolve the issues.

**Edit**
Have to try `php5.6-xml` instead
![screenshot from 2016-06-07 11-17-45](https://cloud.githubusercontent.com/assets/236039/15865735/81b677d6-2ca1-11e6-93af-03112f9269db.png)

Trying, gives an apache error, we'll have to see how it works (we don't use apache)
![screenshot from 2016-06-07 11-18-57](https://cloud.githubusercontent.com/assets/236039/15865777/ac440c34-2ca1-11e6-9415-0e95af4fa5c9.png)

**Comment by Lowell20** [comment]
I think you can bypass these issues by not installing the development packages. We are not using any of them anyways. 

composer install --no-dev

**Comment by AnthonyAstige** [comment]
I think the above updates helped, though we're getting new errors now

## Log

[log.txt](https://github.com/codeforeauclaire/foodtrucks/files/303091/log.txt)

## Screenshots

![1](https://cloud.githubusercontent.com/assets/236039/15866526/a1b770dc-2ca4-11e6-9420-8791bc2efe53.png)
![2](https://cloud.githubusercontent.com/assets/236039/15866531/a527ce9c-2ca4-11e6-92aa-596a59ea339f.png)
![3](https://cloud.githubusercontent.com/assets/236039/15866533/a7ccf2da-2ca4-11e6-9a4a-26b6d1882ce6.png)

**Comment by AnthonyAstige** [comment]
I'm in the middle of running `vmsquickinstall.sh` right now. I've confirmed the script has `composer install --no-dev` however I notice it's output:

> Updating dependencies (**including require-dev**)

I'm not sure if this matters, posting just in case.

## Screenshot

![new](https://cloud.githubusercontent.com/assets/236039/15867119/39400886-2ca7-11e6-8e62-660226641053.png)

**Comment by AnthonyAstige** [comment]
Unassigned myself as I'm not sure offhand what to try next here, and I figure @Lowell20 may have a relatively quick fix.

**Comment by Lowell20** [comment]
After taking a look at the vm install, I feel like we should change a few things starting with a php7.0 setup
The actual problem is just that required php dependencies have not been installed
Is it ok if I try making some changes in the script myself?
Or should we make an appointment and do this together, maybe a hangout

**Comment by AnthonyAstige** [comment]
@Lowell20 Looks like you may have given things a shot. If you've roughly tested your changes feel free to accept your pull request https://github.com/codeforeauclaire/foodtrucks/pull/80 to give the updated script a go.  I'm not too worried about `vmsinstall.sh` as it's broken right now anyways.

**PHP 7**
Glancing at https://github.com/codeforeauclaire/foodtrucks/pull/80/commits/777c3d5fd687c8acf87f143b2a6d67b3a1880006 I'm not sure it'll update to PHP7; VMSs run Ubuntu 14, which will be a bit out of date with the default installs.  Even to get up to 5.6 I have to add a the custom repository `ppa:ondrej/php` (The line `sudo add-apt-repository ppa:ondrej/php -y`). Looks like [the ppa:ondrej/php help page](https://launchpad.net/~ondrej/+archive/ubuntu/php) says it does support php 7 though with `sudo apt-get install -y php7.0`  (Found in [Digital Ocean Guide for PHP7 on Ubuntu 14](https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04)).  I'd guess some of the php plugin names have to be updated to php7 too.

**Comment by Lowell20** [comment]
this should be working now with php7.0 and a few other goodies like xdebug, although I haven't added the necessary xdebug config to the php.ini file yet
